export const TIMELINE_EVENT_TYPES = {
  EVENT_PUBLISHED: { label: 'Event published', variant: 'primary' },
  EVENT_STARTED: { label: 'Event started', variant: 'success' },
  EVENT_COMPLETED: { label: 'Event completed', variant: 'success' },
  TEAM_CREATED: { label: 'Team created', variant: 'primary' },
  TEAM_REACTIVATED: { label: 'Team reactivated', variant: 'success' },
  TEAM_DISQUALIFIED: { label: 'Team disqualified', variant: 'danger' },
  RESULT_PUBLISHED: { label: 'Results published', variant: 'info' },
  CORRECTED_RESULT_REPUBLISHED: { label: 'Corrected results', variant: 'info' },
  APPEAL_WINDOW_OPENED: { label: 'Appeal window opened', variant: 'warning' },
  APPEAL_SUBMITTED: { label: 'Appeal submitted', variant: 'warning' },
  APPEAL_RESOLVED: { label: 'Appeal resolved', variant: 'info' },
  ROUND_ADVANCED: { label: 'Round advanced', variant: 'success' },
  SUBMISSION_CREATED: { label: 'Submission created', variant: 'primary' },
  SUBMISSION_UPDATED: { label: 'Submission updated', variant: 'secondary' },
  SUPPORT_CREATED: { label: 'Support created', variant: 'primary' },
  SUPPORT_IN_PROGRESS: { label: 'Support in progress', variant: 'info' },
  SUPPORT_REOPENED: { label: 'Support reopened', variant: 'warning' },
  SUPPORT_RESOLVED: { label: 'Support resolved', variant: 'success' },
  INCIDENT_SUBMITTED: { label: 'Incident submitted', variant: 'warning' },
  INCIDENT_UNDER_REVIEW: { label: 'Incident under review', variant: 'warning' },
  INCIDENT_RESOLVED: { label: 'Incident resolved', variant: 'info' },
  INCIDENT_DISMISSED: { label: 'Incident dismissed', variant: 'secondary' },
  SUBMISSION_REVIEW_STATUS_CHANGED: { label: 'Submission review updated', variant: 'info' },
  TRACK_RESULTS_FINALIZED: { label: 'Track finalized', variant: 'success' },
  FINAL_RESULTS_FINALIZED: { label: 'Final results finalized', variant: 'success' },
  EVENT_READY_FOR_AWARDS: { label: 'Event ready for awards', variant: 'info' },
  PRIZE_CONFIGURED: { label: 'Prize configured', variant: 'secondary' },
  PRIZE_AWARDED: { label: 'Prize awarded', variant: 'warning' },
  SEED_CONFIRMED: { label: 'Seed confirmed', variant: 'info' },
  RECOGNITION_AWARDED: { label: 'Recognition earned', variant: 'success' },
  RECOGNITION_RESTORED: { label: 'Recognition restored', variant: 'success' },
};

export const timelineTypeMeta = (type) =>
  TIMELINE_EVENT_TYPES[type] || {
    label: type ? type.replaceAll('_', ' ').toLowerCase() : 'Timeline milestone',
    variant: 'secondary',
  };
