package vn.edu.fpt.seal.common.enums;

public enum AuditAction {
    CREATE, UPDATE, DELETE,
    APPROVE_USER, REJECT_USER,
    SUBMIT_PROJECT, SCORE_SUBMISSION, UPDATE_SCORE,
    DISQUALIFY_TEAM, PROMOTE_TEAM, ELIMINATE_TEAM,
    CREATE_INCIDENT, PROCESS_INCIDENT, RESOLVE_INCIDENT, REJECT_INCIDENT,
    PUBLISH_RESULTS,
    FINALIZE_RESULTS, ASSIGN_SEED, REMOVE_SEED,
    TEAM_RECOGNITION_AWARDED, TEAM_RECOGNITION_REVOKED, TEAM_RECOGNITION_RESTORED
}
