package vn.edu.fpt.seal.modules.timeline;

public enum TimelineEventType {
    EVENT_PUBLISHED, EVENT_REGISTRATION_CLOSED, EVENT_STARTED, EVENT_COMPLETED, EVENT_CANCELLED,
    TEAM_CREATED, TEAM_REACTIVATED, TEAM_DISQUALIFIED, TEAM_PROMOTED, TEAM_ELIMINATED,
    ROUND_STARTED, RESULT_PUBLISHED, APPEAL_WINDOW_OPENED, ROUND_PAUSED_FOR_APPEAL,
    RESULT_RECALCULATION_REQUIRED, CORRECTED_RESULT_REPUBLISHED, ROUND_READY_TO_ADVANCE,
    ROUND_ADVANCED, FINAL_ROUND_READY_FOR_AWARDS, COMPETITION_RESUMED,
    SUBMISSION_CREATED, SUBMISSION_UPDATED, SUBMISSION_REVIEW_STATUS_CHANGED,
    APPEAL_SUBMITTED, APPEAL_CLARIFICATION_REQUESTED, APPEAL_REJECTED,
    APPEAL_ACCEPTED, APPEAL_ACCEPTED_RECALCULATION, APPEAL_RESOLVED,
    INCIDENT_SUBMITTED, INCIDENT_UNDER_REVIEW, INCIDENT_RESOLVED, INCIDENT_DISMISSED,
    SUPPORT_CREATED, SUPPORT_IN_PROGRESS, SUPPORT_AWAITING_REPORTER, SUPPORT_RESOLVED, SUPPORT_REOPENED,
    TRACK_RESULTS_FINALIZED, FINAL_RESULTS_FINALIZED, EVENT_READY_FOR_AWARDS,
    HISTORICAL_FINISHES_CREATED, PRIZE_CONFIGURED, PRIZE_AWARDED,
    SEED_CONFIRMED, SEED_OVERRIDDEN, SEED_REMOVED,
    RECOGNITION_AWARDED, RECOGNITION_REVOKED, RECOGNITION_RESTORED
}
