package vn.edu.fpt.seal.modules.appeal.service;
import lombok.RequiredArgsConstructor; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import vn.edu.fpt.seal.common.enums.*; import vn.edu.fpt.seal.common.exception.ApiException; import vn.edu.fpt.seal.modules.appeal.dto.AppealDtos; import vn.edu.fpt.seal.modules.appeal.entity.Appeal; import vn.edu.fpt.seal.modules.appeal.repository.AppealRepository;
import vn.edu.fpt.seal.modules.participant.repository.RoundParticipantRepository; import vn.edu.fpt.seal.modules.resultversion.repository.RoundResultVersionRepository;
import vn.edu.fpt.seal.modules.round.entity.Round; import vn.edu.fpt.seal.modules.round.repository.RoundRepository; import vn.edu.fpt.seal.modules.round.service.CompetitionLifecycleService;
import vn.edu.fpt.seal.modules.team.entity.*; import vn.edu.fpt.seal.modules.team.repository.TeamMemberRepository; import vn.edu.fpt.seal.modules.user.entity.User; import vn.edu.fpt.seal.modules.user.repository.UserRepository;
import vn.edu.fpt.seal.security.CurrentUser; import java.time.*; import java.util.*;
import org.springframework.beans.factory.annotation.Autowired; import vn.edu.fpt.seal.modules.timeline.*; import vn.edu.fpt.seal.modules.timeline.dto.TimelineEventRequest; import vn.edu.fpt.seal.modules.timeline.service.TimelineService;
@Service @RequiredArgsConstructor
public class AppealService {
 private final AppealRepository appeals; private final RoundRepository rounds; private final RoundResultVersionRepository versions;
 private final RoundParticipantRepository participants; private final TeamMemberRepository members; private final UserRepository users;
 private final CompetitionLifecycleService lifecycle; private final Clock clock;
 @Autowired private TimelineService timeline;
 @Transactional public AppealDtos.Response create(AppealDtos.Create req,Authentication auth){
  CurrentUser c=current(auth); Round r=rounds.findById(req.roundId()).orElseThrow(()->ApiException.notFound("Round not found"));
  TeamMember leader=members.findByUserIdOrderByJoinedAtDesc(c.getId()).stream().filter(m->m.getRole()==TeamMemberRole.leader&&m.getTeam().getTrack().getEvent().getId().equals(r.getTrack().getEvent().getId())).findFirst().orElseThrow(()->ApiException.forbidden("Only the current event team leader may appeal"));
  Team team=leader.getTeam(); if(!participants.existsByRoundIdAndTeamId(r.getId(),team.getId()))throw ApiException.forbidden("Team did not participate in this round");
  var v=versions.findByRoundIdAndStatus(r.getId(),"published").orElseThrow(()->ApiException.badRequest("No active published result version"));
  LocalDateTime now=LocalDateTime.now(clock); if(!now.isBefore(v.getAppealDeadline()))throw ApiException.badRequest("Appeal deadline has expired");
  if(appeals.existsByTeamIdAndResultVersionId(team.getId(),v.getId()))throw ApiException.conflict("Team already appealed this result version");
  User user=users.findById(c.getId()).orElseThrow(); Appeal a=appeals.save(Appeal.builder().event(r.getTrack().getEvent()).round(r).team(team).submittedBy(user).resultVersion(v)
   .reason(req.reason().trim()).status("PENDING").resultPublishedAt(v.getPublishedAt()).appealDeadline(v.getAppealDeadline()).createdAt(now).build());
  r.setLifecycleState(RoundLifecycleState.PAUSED_FOR_APPEAL);
  record(a,TimelineEventType.APPEAL_SUBMITTED,TimelineScope.TEAM_PRIVATE,"Appeal submitted","The team submitted an appeal","submitted");
  record(a,TimelineEventType.ROUND_PAUSED_FOR_APPEAL,TimelineScope.EVENT_PARTICIPANTS,"Competition paused for appeal","Round progression is paused during appeal review","pause");
  return map(a);
 }
 @Transactional public List<AppealDtos.Response> list(UUID eventId,String status){if(eventId==null)throw ApiException.badRequest("eventId is required");return appeals.findByEventIdOrderByCreatedAtDesc(eventId).stream().filter(a->status==null||a.getStatus().equalsIgnoreCase(status)).map(this::map).toList();}
 @Transactional public List<AppealDtos.Response> team(UUID teamId,Authentication auth){CurrentUser c=current(auth);boolean coordinator=c.getRoles().contains("coordinator");if(!coordinator&&!members.existsByTeamIdAndUserId(teamId,c.getId()))throw ApiException.forbidden("Out of scope");return appeals.findByTeamIdOrderByCreatedAtDesc(teamId).stream().map(this::map).toList();}
 @Transactional public AppealDtos.Response get(UUID id,Authentication auth){Appeal a=find(id);CurrentUser c=current(auth);if(!c.getRoles().contains("coordinator")&&!members.existsByTeamIdAndUserId(a.getTeam().getId(),c.getId()))throw ApiException.forbidden("Out of scope");return map(a);}
 @Transactional public AppealDtos.Response respond(UUID id,AppealDtos.Respond req){Appeal a=find(id);if(!a.getStatus().equals("PENDING"))throw ApiException.conflict("Appeal already resolved");a.setResponse(req.response().trim());a.setUpdatedAt(LocalDateTime.now(clock));record(a,TimelineEventType.APPEAL_CLARIFICATION_REQUESTED,TimelineScope.TEAM_PRIVATE,"Appeal clarification requested","The coordinator requested clarification","clarification");return map(a);}
 @Transactional public AppealDtos.Response resolve(UUID id,AppealDtos.Resolve req,Authentication auth){Appeal a=find(id);if(!a.getStatus().equals("PENDING"))throw ApiException.conflict("Appeal already resolved");String d=req.status().toUpperCase();if(!Set.of("REJECTED","ACCEPTED").contains(d))throw ApiException.badRequest("Decision must be ACCEPTED or REJECTED");boolean recalc=d.equals("ACCEPTED")&&Boolean.TRUE.equals(req.recalculationRequired());a.setStatus(d);a.setDecision(d);a.setRecalculationRequired(recalc);a.setResponse(req.response());a.setResolvedBy(users.findById(current(auth).getId()).orElseThrow());a.setResolvedAt(LocalDateTime.now(clock));lifecycle.resolved(a.getRound(),recalc);TimelineEventType type=d.equals("REJECTED")?TimelineEventType.APPEAL_REJECTED:recalc?TimelineEventType.APPEAL_ACCEPTED_RECALCULATION:TimelineEventType.APPEAL_ACCEPTED;record(a,type,TimelineScope.TEAM_PRIVATE,d.equals("REJECTED")?"Appeal rejected":"Appeal accepted","The appeal decision is available","resolved:"+d+":"+recalc);record(a,TimelineEventType.APPEAL_RESOLVED,TimelineScope.TEAM_PRIVATE,"Appeal resolved","The appeal review is complete","resolved");if(recalc)record(a,TimelineEventType.RESULT_RECALCULATION_REQUIRED,TimelineScope.COORDINATOR_PRIVATE,"Result recalculation required","A result version requires controlled recalculation","recalculation");return map(a);}
 private Appeal find(UUID id){return appeals.findWithRelationsById(id).orElseThrow(()->ApiException.notFound("Appeal not found"));}
 private void record(Appeal a,TimelineEventType type,TimelineScope scope,String title,String description,String suffix){if(timeline==null)return;timeline.record(new TimelineEventRequest(a.getEvent().getId(),scope==TimelineScope.EVENT_PARTICIPANTS?null:a.getTeam().getId(),a.getRound().getId(),a.getRound().getTrack().getId(),type,TimelineSourceType.APPEAL,a.getId(),scope,title,description,null,"appeal:"+a.getId()+":"+suffix));}
 private CurrentUser current(Authentication a){if(a==null||!(a.getPrincipal() instanceof CurrentUser c))throw ApiException.unauthorized("Authentication required");return c;}
 private AppealDtos.Response map(Appeal a){lifecycle.refresh(a.getRound());long remaining=a.getAppealDeadline()==null?0:Math.max(0,Duration.between(LocalDateTime.now(clock),a.getAppealDeadline()).getSeconds());Integer version=a.getResultVersion()==null?null:a.getResultVersion().getVersionNumber();return new AppealDtos.Response(a.getId(),a.getEvent().getId(),a.getRound().getId(),a.getRound().getName(),a.getTeam().getId(),a.getTeam().getName(),a.getSubmittedBy().getId(),a.getReason(),a.getStatus(),a.getResponse(),a.getDecision(),a.isRecalculationRequired(),version,a.getResultPublishedAt(),a.getAppealDeadline(),a.getCreatedAt(),a.getResolvedAt(),a.getRound().getLifecycleState().name(),remaining);}
}
