package vn.edu.fpt.seal.modules.university.service; import lombok.RequiredArgsConstructor; import org.springframework.data.domain.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import vn.edu.fpt.seal.common.exception.ApiException; import vn.edu.fpt.seal.modules.university.dto.*; import vn.edu.fpt.seal.modules.university.entity.*; import vn.edu.fpt.seal.modules.university.mapper.UniversityMapper; import vn.edu.fpt.seal.modules.university.repository.*; import java.util.UUID;
@Service @RequiredArgsConstructor public class UniversityService{private final UniversityRepository universityRepo; private final CampusRepository campusRepo;
 @Transactional(readOnly=true) public Page<UniversityResponse> universities(Pageable p){return universityRepo.findAll(p).map(UniversityMapper::toResponse);} @Transactional(readOnly=true) public UniversityResponse getUniversity(UUID id){return UniversityMapper.toResponse(findUniversity(id));}
 @Transactional public UniversityResponse createUniversity(UniversityRequest r){String n=r.name().trim(); if(universityRepo.existsByNameIgnoreCase(n)) throw ApiException.conflict("University name already exists"); return UniversityMapper.toResponse(universityRepo.save(University.builder().name(n).shortName(trim(r.shortName())).country(trim(r.country())).build()));}
 @Transactional public UniversityResponse updateUniversity(UUID id,UniversityRequest r){University u=findUniversity(id); String n=r.name().trim(); if(!n.equalsIgnoreCase(u.getName())&&universityRepo.existsByNameIgnoreCase(n)) throw ApiException.conflict("University name already exists"); u.setName(n); u.setShortName(trim(r.shortName())); u.setCountry(trim(r.country())); return UniversityMapper.toResponse(u);} @Transactional public void deleteUniversity(UUID id){universityRepo.delete(findUniversity(id));}
 @Transactional(readOnly=true) public Page<CampusResponse> campuses(UUID universityId,Pageable p){Page<Campus> page=universityId==null?campusRepo.findAll(p):campusRepo.findByUniversityId(universityId,p); return page.map(UniversityMapper::toResponse);} @Transactional(readOnly=true) public CampusResponse getCampus(UUID id){return UniversityMapper.toResponse(findCampus(id));}
 @Transactional public CampusResponse createCampus(CampusRequest r){University u=findUniversity(r.universityId()); String n=r.name().trim(); if(campusRepo.existsByUniversityIdAndNameIgnoreCase(r.universityId(),n)) throw ApiException.conflict("Campus name already exists in university"); return UniversityMapper.toResponse(campusRepo.save(Campus.builder().university(u).name(n).address(trim(r.address())).city(trim(r.city())).build()));}
 @Transactional public CampusResponse updateCampus(UUID id,CampusRequest r){Campus c=findCampus(id); University u=findUniversity(r.universityId()); String n=r.name().trim(); if((!u.getId().equals(c.getUniversity().getId())||!n.equalsIgnoreCase(c.getName()))&&campusRepo.existsByUniversityIdAndNameIgnoreCase(u.getId(),n)) throw ApiException.conflict("Campus name already exists in university"); c.setUniversity(u); c.setName(n); c.setAddress(trim(r.address())); c.setCity(trim(r.city())); return UniversityMapper.toResponse(c);} @Transactional public void deleteCampus(UUID id){campusRepo.delete(findCampus(id));}
 private University findUniversity(UUID id){return universityRepo.findById(id).orElseThrow(()->ApiException.notFound("University not found: "+id));} private Campus findCampus(UUID id){return campusRepo.findWithUniversityById(id).orElseThrow(()->ApiException.notFound("Campus not found: "+id));} private String trim(String s){return s==null?null:s.trim();}}
